language: node_js
node_js:
  - node
notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
script:
  - npm install codecov -g
  - yarn build
  - yarn test --coverage
after_success:
  - codecov
